export const HOME: string = '/';
export const SIGN_UP: string = '/user/sign_up'; //회원가입
export const SIGN_UP_EMAIL: string = '/user/sign_up_email';
export const SIGN_IN: string = '/user/sign_in'; //로그인
export const SIGN_IN_EMAIL: string = '/user/sign_in_email';
export const DAY_TOUR: string = '/day_tour';
export const ONLINE_EXPERIENCE: string = '/online_experience';
export const TOUR_DETAIL: string = '/detail/:id';
export const CREATE_TRIP: string = '/create_trip';
export const CALENDAR: string = '/calendar';
export const ACCOUNT: string = '/account';
export const ADMIN: string = '/admin';
export const PASSWORD_FORGET: string = '/pw-forget';
export const BUCKET_LIST: string = '/bucket_list';
export const MESSEGE: string = '/messenger/rooms';
export const TRAVELER_RESERVATION: string = '/traveler/reservations';
